/*
 * Transaction API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.dto.TransactionDTO;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionPage
 */
class TransactionPageTest {
    private final TransactionPage model = new TransactionPage();

    /**
     * Model tests for TransactionPage
     */
    @Test
    void testTransactionPage() {
        // TODO: test TransactionPage
    }

    /**
     * Test the property 'items'
     */
    @Test
    void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'count'
     */
    @Test
    void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'offset'
     */
    @Test
    void offsetTest() {
        // TODO: test offset
    }

    /**
     * Test the property 'limit'
     */
    @Test
    void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'total'
     */
    @Test
    void totalTest() {
        // TODO: test total
    }

}
